### ISSUE TITLE
NPE when validating an array query parameter

### ISSUE THREAD

**Issue by Dimitris-Christodoulou** [openapi4j/openapi4j#108]
**Describe the bug**
A `NullPointerException` is thrownwhen validating an array query parameter using the `OperationValidator` in version 1.0 of openapi4j.

**To Reproduce**
Run the following Java program:
```java
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Collections;
import org.openapi4j.core.exception.ResolutionException;
import org.openapi4j.core.validation.ValidationException;
import org.openapi4j.operation.validator.model.Request;
import org.openapi4j.operation.validator.model.Request.Method;
import org.openapi4j.operation.validator.model.impl.DefaultRequest;
import org.openapi4j.operation.validator.validation.OperationValidator;
import org.openapi4j.parser.OpenApi3Parser;
import org.openapi4j.parser.model.v3.OpenApi3;
import org.openapi4j.parser.model.v3.Operation;
import org.openapi4j.parser.model.v3.Path;
import org.openapi4j.schema.validator.ValidationData;

public class QueryArrayBug {

  public static void main(String[] args)
    throws IOException, ResolutionException, ValidationException {
    final String apiDefinition =
      "openapi: 3.0.0\n"
        + "info:\n"
        + "  title: Sample API\n"
        + "  description: A sample API to be used in unit-tests\n"
        + "  version: v0\n"
        + "paths:\n"
        + "  /users:\n"
        + "    get:\n"
        + "      operationId: GetUsers\n"
        + "      parameters:\n"
        + "        - name: userID\n"
        + "          in: query\n"
        + "          required: true\n"
        + "          schema:\n"
        + "            $ref: '#/components/schemas/UserIDArray'\n"
        + "      responses:\n"
        + "        '200':\n"
        + "          description: The users\n"
        + "          content:\n"
        + "            application/json:\n"
        + "              schema:\n"
        + "                $ref: '#/components/schemas/UserArray'\n"
        + "\n"
        + "components:\n"
        + "  schemas:\n"
        + "    UserArray:\n"
        + "      type: array\n"
        + "      items:\n"
        + "        type: string\n"
        + "\n"
        + "    UserID:\n"
        + "      type: integer\n"
        + "      format: int64\n"
        + "\n"
        + "    UserIDArray:\n"
        + "      type: array\n"
        + "      items:\n"
        + "        $ref: '#/components/schemas/UserID'\n"
        + "\n";

    final File yaml = Files
      .write(Files.createTempFile("openapi", ".yaml"), apiDefinition.getBytes()).toFile();
    final DefaultRequest.Builder builder = new DefaultRequest.Builder("/users", Method.GET);

    builder.body(null);
    builder.cookies(Collections.emptyMap());
    builder.headers(Collections.emptyMap());

    builder.query("userID=1&userID=2&userID=3");

    final Request request = builder.build();

    final OpenApi3 openApi3 = new OpenApi3Parser().parse(yaml, false);
    final Path path = openApi3.getPathItemByOperationId("GetUsers");
    final Operation operation = openApi3.getOperationById("GetUsers");

    final OperationValidator validator = new OperationValidator(openApi3, path, operation);
    final ValidationData<Void> data = new ValidationData<>();
    validator.validateQuery(request, data);
    assert data.isValid();
  }
}

```

**Expected behavior**
Expected the validation to succeed without any validation messages or exceptions.

**Additional context**
In this line of code `FormStyleConverter.getArrayValues(FormStyleConverter.java:61)`:

```
 return TypeConverter.instance().convertArray(param.getSchema().getItemsSchema(), values);
```

`param.getSchema().getItemsSchema()` contains a schema with a schema `$ref` which is not resolved. As a result the `switch (schema.getSupposedType())` statement in `TypeConverter.convertArray(TypeConverter.java:75)` throws a `NullPointerException` because `schema.getSupposedType()` is `null`.  

**Reproducer**
Se above Java code to reproduce.

**Stack Trace**
```
Exception in thread "main" java.lang.NullPointerException
	at org.openapi4j.operation.validator.util.convert.TypeConverter.convertArray(TypeConverter.java:75)
	at org.openapi4j.operation.validator.util.convert.style.FormStyleConverter.getArrayValues(FormStyleConverter.java:61)
	at org.openapi4j.operation.validator.util.convert.style.FormStyleConverter.convert(FormStyleConverter.java:35)
	at org.openapi4j.operation.validator.util.convert.FormUrlConverter.convert(FormUrlConverter.java:80)
	at org.openapi4j.operation.validator.util.convert.ParameterConverter.queryToNode(ParameterConverter.java:144)
	at org.openapi4j.operation.validator.validation.OperationValidator.validateQuery(OperationValidator.java:189)
```

**Comment by llfbandit** [comment]
I confirm the issue in 1.0. This is a regression from #106 .
Sorry the inconvenience, I forgot to unwrap nested $ref for converters.

I'm on it.
In the meantime, you can revert to 0.9 if needed.

**Comment by Dimitris-Christodoulou** [comment]
> I confirm the issue in 1.0. This is a regression from #106 .
> Sorry the inconvenience, I forgot to unwrap nested $ref for converters.
> 
> I'm on it.
> In the meantime, you can revert to 0.9 if needed.

Hi,

Thank you for the quick response. It's a blocker so staying on 0.9 until this is resolved.

**Comment by llfbandit** [comment]
Almost done in fix/converter_unwrap_nested_ref branch. Maybe you're able to make some tests on your side.
I just need to add more tests before releasing a new version.

**Comment by llfbandit** [comment]
The changes imply some breaking changes:
`Schema.getSupposedType` now requires the context.
Some others too, but at low a level in Operation Validator module.
Nobody should be affected by those since the affected methods shouldn't be used directly/externally.

**Comment by Dimitris-Christodoulou** [comment]
> The changes imply some breaking changes:
> `Schema.getSupposedType` now requires the context.
> Some others too, but at low a level in Operation Validator module.
> Nobody should be affected by those since the affected methods shouldn't be used directly/externally.

Thank you for the quick turnaround in releasing 1.0.1! I will give it a try on Monday.

**Comment by llfbandit** [comment]
Closing due to inactivity. Feel free to reopen it if the fix doesn't fully resolve the issue.
