### ISSUE TITLE
multipart/form-data Request with additional property throws Null pointer exception

### ISSUE THREAD

**Issue by aravindc26** [openapi4j/openapi4j#126]
1. set additionProperty to true, in the request body schema definition. 
2. raise a multipart/form-data request with a property not defined in the request body schema

```
java.lang.NullPointerException
	at org.openapi4j.operation.validator.util.convert.MultipartConverter.convertToJsonNode(MultipartConverter.java:140)
	at org.openapi4j.operation.validator.util.convert.MultipartConverter.mapValue(MultipartConverter.java:94)
	at org.openapi4j.operation.validator.util.convert.MultipartConverter.convert(MultipartConverter.java:56)
	at org.openapi4j.operation.validator.util.convert.ContentConverter.multipartToNode(ContentConverter.java:62)
	at org.openapi4j.operation.validator.util.convert.ContentConverter.convert(ContentConverter.java:43)
	at org.openapi4j.operation.validator.model.impl.Body.getContentAsNode(Body.java:111)
	at org.openapi4j.operation.validator.validation.BodyValidator.validate(BodyValidator.java:47)
	at org.openapi4j.operation.validator.validation.OperationValidator.validateBodyWithContentType(OperationValidator.java:307)
	at org.openapi4j.operation.validator.validation.OperationValidator.validateBody(OperationValidator.java:260)
	at org.openapi4j.operation.validator.validation.RequestValidator.validate(RequestValidator.java:234)
	at org.openapi4j.operation.validator.validation.RequestValidator.validate(RequestValidator.java:133)
```

**Comment by llfbandit** [comment]
Hi and welcome,

Thanks for the report and PR, I'll check this soon.

**Comment by llfbandit** [comment]
This should be fixed in 1.0.4-SNAPSHOT.
Are you able to confirm?

**Comment by aravindc26** [comment]
The latest snapshot is not available yet. Will let you know once it is available.

**Comment by llfbandit** [comment]
You must add snapshot repository. URL is available from badge in readme.md

**Comment by aravindc26** [comment]
@llfbandit the latest snapshot is working !
